<?php

use Illuminate\Database\Seeder;

class RelacionesGeneros extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('generos_movies')->insert([
            'movies_id'=>'1',
            'generos_id'=>'1'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'1',
            'generos_id'=>'7'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'2',
            'generos_id'=>'2'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'2',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'3',
            'generos_id'=>'1'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'3',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'3',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'3',
            'generos_id'=>'7'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'4',
            'generos_id'=>'2'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'4',
            'generos_id'=>'3'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'5',
            'generos_id'=>'1'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'5',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'6',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'7',
            'generos_id'=>'1'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'7',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'8',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'8',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'9',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'9',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'10',
            'generos_id'=>'5'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'11',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'11',
            'generos_id'=>'5'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'12',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'12',
            'generos_id'=>'5'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'12',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'13',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'13',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'14',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'15',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'15',
            'generos_id'=>'5'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'16',
            'generos_id'=>'2'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'17',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'17',
            'generos_id'=>'5'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'17',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'18',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'18',
            'generos_id'=>'6'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'19',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'19',
            'generos_id'=>'5'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'20',
            'generos_id'=>'4'
        ]);
        DB::table('generos_movies')->insert([
            'movies_id'=>'21',
            'generos_id'=>'1'
        ]);
    }
}
