<?php

use App\people;
use App\movie;
use Illuminate\Database\Seeder;

class RelacionesActores extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'3',
            'movie_id'=>'1'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'5',
            'movie_id'=>'2'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'6',
            'movie_id'=>'2'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'7',
            'movie_id'=>'2'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'8',
            'movie_id'=>'2'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'3',
            'movie_id'=>'3'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'58',
            'movie_id'=>'4'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'59',
            'movie_id'=>'4'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'3',
            'movie_id'=>'5'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'100',
            'movie_id'=>'6'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'101',
            'movie_id'=>'6'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'102',
            'movie_id'=>'6'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'103',
            'movie_id'=>'6'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'104',
            'movie_id'=>'6'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'3',
            'movie_id'=>'7'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'113',
            'movie_id'=>'8'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'114',
            'movie_id'=>'8'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'115',
            'movie_id'=>'8'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'116',
            'movie_id'=>'8'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'124',
            'movie_id'=>'9'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'125',
            'movie_id'=>'9'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'126',
            'movie_id'=>'9'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'128',
            'movie_id'=>'9'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'135',
            'movie_id'=>'10'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'136',
            'movie_id'=>'10'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'149',
            'movie_id'=>'11'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'150',
            'movie_id'=>'11'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'151',
            'movie_id'=>'11'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'158',
            'movie_id'=>'12'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'159',
            'movie_id'=>'12'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'160',
            'movie_id'=>'12'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'166',
            'movie_id'=>'13'
        ]);DB::table('people_actuan_movies')->insert([
            'people_id'=>'167',
            'movie_id'=>'13'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'168',
            'movie_id'=>'13'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'174',
            'movie_id'=>'14'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'175',
            'movie_id'=>'14'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'177',
            'movie_id'=>'14'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'186',
            'movie_id'=>'15'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'187',
            'movie_id'=>'15'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'188',
            'movie_id'=>'15'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'189',
            'movie_id'=>'15'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'202',
            'movie_id'=>'16'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'203',
            'movie_id'=>'16'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'204',
            'movie_id'=>'16'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'218',
            'movie_id'=>'17'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'219',
            'movie_id'=>'17'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'220',
            'movie_id'=>'17'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'229',
            'movie_id'=>'18'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'230',
            'movie_id'=>'18'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'231',
            'movie_id'=>'18'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'232',
            'movie_id'=>'18'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'244',
            'movie_id'=>'19'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'245',
            'movie_id'=>'19'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'244',
            'movie_id'=>'20'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'253',
            'movie_id'=>'20'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'254',
            'movie_id'=>'20'
        ]);
        DB::table('people_actuan_movies')->insert([
            'people_id'=>'1',
            'movie_id'=>'21'
        ]);
        

    }
}
